name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build && mkdir -p releases && find app/build/ -type f -name \*\.apk -exec mv {} releases/com.volla.vollaboard_$GITHUB_RUN_ID.apk \; && ls -l releases

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: ./releases
        signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE_CONTENTS }}
        signedReleaseFile: ./releases/signed
        alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        keyPassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}


    - name: Upload Apk to Nightly Repository
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'drone'
        server: 'volla.tech'
        port: 22
        ssh_private_key: '${{ secrets.FDROID_DEPLOY_KEY }}'
        local_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
        remote_path: '/fdroid-nightly.volla.tech/builds/volla/vollaboard/'
        args: '-o CheckHostIP=no -o StrictHostKeyChecking=no'

    - name: Upload Apk to Release Repository
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: 'drone'
        server: 'volla.tech'
        port: 22
        ssh_private_key: '${{ secrets.FDROID_DEPLOY_KEY }}'
        local_path: ${{ steps.sign_app.outputs.signedReleaseFile }}
        remote_path: '/fdroid.volla.tech/builds/volla/vollaboard/'
        args: '-o CheckHostIP=no -o StrictHostKeyChecking=no'
