name: Android CI

on:
  push:
    branches: [ "volla-14" ]
  pull_request:
    branches: [ "volla-14" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew build
          mkdir -p releases
          find app/build/ -type f -name "Vollaboard_Universal.apk" -exec mv {} releases/com.volla.vollaboard.apk \;
          ls -l releases

      - name: Install Android SDK Build-Tools
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.0

      # Decode the base64 keystore and save it as keystore.jks
      - name: Create keystore file from base64
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_FILE_CONTENTS }}" | base64 --decode > keystore.jks

      - name: Align APK
        run: |
          ${ANDROID_HOME}/build-tools/33.0.0/zipalign -v 4 releases/com.volla.vollaboard.apk releases/com.volla.vollaboard-aligned.apk
        shell: bash

      - name: Sign APK manually
        run: |
          ${ANDROID_HOME}/build-tools/33.0.0/apksigner sign --ks keystore.jks --ks-key-alias ${{ secrets.ANDROID_KEYSTORE_ALIAS }} --ks-pass pass:${{ secrets.ANDROID_KEYSTORE_PASS }} --key-pass pass:${{ secrets.ANDROID_KEYSTORE_PASS }} --out releases/com.volla.vollaboard-signed.apk releases/com.volla.vollaboard-aligned.apk
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: com.volla.vollaboard-signed.apk
          path: releases/com.volla.vollaboard-signed.apk
          
      - name: Upload Apk to Nightly Repository
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'drone'
          server: 'volla.tech'
          port: 22
          ssh_private_key: '${{ secrets.FDROID_DEPLOY_KEY }}'
          local_path: releases/com.volla.vollaboard-signed.apk
          remote_path: '/fdroid-nightly.volla.tech/builds/volla/vollaboard/'
          args: '-o CheckHostIP=no -o StrictHostKeyChecking=no'

      - name: Upload Apk to Release Repository
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'drone'
          server: 'volla.tech'
          port: 22
          ssh_private_key: '${{ secrets.FDROID_DEPLOY_KEY }}'
          local_path: releases/com.volla.vollaboard-signed.apk
          remote_path: '/fdroid.volla.tech/builds/volla/vollaboard/'
          args: '-o CheckHostIP=no -o StrictHostKeyChecking=no'
